name: CI/CD pipeline for MERN App
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: build & push back and front end images to docker hub
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: docker login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build and push frontend
      id: frontend-build-and-push
      uses: docker/build-push-action@v3
      with:
        context: frontend/
        file: frontend/Dockerfile
        push: true
        tags: aasquith/react-app-frontend:latest