name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./coffee_front_end

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Install Dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test --if-present
      
      - name: Build the frontend
        run: npm run build

      - name: List dist contents
        run: ls -la ./dist

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_PROJECT_ID: ${{ secrets.NETLIFY_PROJECT_ID }}
        timeout-minutes: 1


      

        